### ISSUE TITLE
onlinelearning

### ISSUE THREAD

**Issue by vwoloszyn** [INK-USC/AlpacaTag#8]
Hi,

I've followed the installation procedures (https://github.com/INK-USC/AlpacaTag/wiki/Installation), everything fine. However, when I turn on active learning, I get the following error:

10/Oct/2019 09:02:33] "PATCH /api/projects/27/docs/2162 HTTP/1.1" 200 956
[10/Oct/2019 09:02:33] "GET /api/projects/27/progress/ HTTP/1.1" 200 25
[10/Oct/2019 09:02:33] "GET /api/projects/27/progress/ HTTP/1.1" 200 25
[10/Oct/2019 09:02:45] "GET /api/projects/27/progress/ HTTP/1.1" 200 25
Internal Server Error: /api/projects/27/onlinelearning/
Traceback (most recent call last):
  File "/home/adminuser/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/adminuser/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adminuser/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adminuser/anaconda3/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/adminuser/anaconda3/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/adminuser/anaconda3/lib/python3.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/adminuser/anaconda3/lib/python3.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/adminuser/anaconda3/lib/python3.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/adminuser/alpaca/AlpacaTag/annotation/AlpacaTag/server/api.py", line 582, in post
    alpaca_online_learning(train_docs, annotations, setting_data['epoch'], setting_data['batch'])
  File "/home/adminuser/alpaca/AlpacaTag/annotation/AlpacaTag/server/api.py", line 69, in alpaca_online_learning
    response = alpaca_client.online_learning(train_docs, annotations, epoch, batch)
AttributeError: 'NoneType' object has no attribute 'online_learning'
[10/Oct/2019 09:02:45] "POST /api/projects/27/onlinelearning/ HTTP/1.1" 500 16777

**Comment by andreser09** [comment]
Hi @vwoloszyn. Did you mange to solve this issue? 
Thanks

**Comment by EndlessDistance** [comment]
> 

You must deploy a AlpacaClient on port 5555&5556, but I didn't find documentation on how to deploy it.
